normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
wrap_comments = true