name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - name: install cargo tools
        run: |
          rustup component add rustfmt
          rustup component add clippy
          cargo install cargo-audit
      - name: cargo build --verbose
        run: cargo build --verbose
      - name: cargo check --verbose
        run: cargo check --verbose
      - name: cargo fmt --verbose -- --check
        run: cargo fmt --verbose -- --check
      - name: cargo clippy --verbose -- -A dead-code
        run: cargo clippy --verbose -- -A dead-code
      - name: cargo build --verbose
        run: cargo build --verbose
      - name: cargo test --verbose -- --skip db
        run: cargo test --verbose -- --skip db
      - name: cargo doc --verbose
        run: cargo doc --verbose
      - name: cargo audit
        run: cargo audit
